### ISSUE TITLE
Won't recognize Wii guitar or 6050

### ISSUE THREAD

**Issue by oboewan42** [sanjay900/guitar-configurator#10]
I wired up a Wii adapter using a 5V Pro Micro clone, a voltage regulator, and a nunchuk breakout. Everything is wired correctly and I can access the guitar just fine via the NintendoExtensionCtrl library.

However, when I try setting up the adapter using the configurator, then open the Windows controller tester, it doesn't respond to any inputs. The top left corner of the configurator window says "Ardwiino/Arduino Pro Micro (5V)/XInput Guitar Hero Guitar/Wii Unknown Extension".

**Comment by sanjay900** [comment]
Odd, I presume you've tried unplugging and replugging after programming?

**Comment by oboewan42** [comment]
Yeah, both on the guitar end and on the USB end.

**Comment by oboewan42** [comment]
Did some more testing. Tried adding a 6050 for tilt, but it wouldn't recognize it either.
Then, I tried changing to direct mode - it'll detect the pins, but not the 6050. 
Using the Arduino IDE I can read the 6050 just fine.

Conclusion - it's probably something to do with the i2c bus in general.

**Comment by sanjay900** [comment]
Odd, it used to work just fine so I'm not really sure what's happened there, do you want to try an older build and see if one of those works?

**Comment by oboewan42** [comment]
Looks like it broke between 8.4.7 and 8.5.1

**Comment by oboewan42** [comment]
Also, this is apparently unrelated, but tilt output is really erratic if I have "Invert" checked, and there's no option to calibrate, if I'm using a 6050.

**Comment by sanjay900** [comment]
are you using the right axis?

**Comment by oboewan42** [comment]
Yeah, it looks like the issue is that if I have it set to "inverted", it'll blink between the inverted and non-inverted value. As a workaround I just mounted my 6050 upside down.

**Comment by oboewan42** [comment]
Switched to a 3.3V Pro Micro, updated back to 8.5.4, and that appears to have fixed both the main issue and the inverted-axis issue. However, there's another issue here: the tilt sensor only shows up in joy.cpl, not in Clone Hero.

**Comment by oboewan42** [comment]
I also noticed that, if I open up joy.cpl's calibration tool and check "Display Raw Data", the range for the tilt axis is different based on which Pro Micro I'm using. (On the 3.3V model, it ranges from 0-63, while on the 5V model, it ranges from 0-65535.)

**Comment by NickBonet** [comment]
I experienced similar issues with Wii guitars not being recognized on 8.5.4, both on an adapter I just built and one of my adapters I updated for testing purposes. At first I thought the build went bad but noticed the same behavior on my old adapter that updated within 8.5.4.

**Comment by sanjay900** [comment]
Yeah, I'm in the process of rewriting everything so I don't really want to
debug this issue

**Comment by sanjay900** [comment]
i have a fix on this old firmware but am waiting for some azure fixes before i can push out a preview build, ill have one out tomorrow.

**Comment by sanjay900** [comment]
https://github.com/sanjay900/guitar-configurator/releases/tag/preview
