### ISSUE TITLE
Rockband drums

### ISSUE THREAD

**Issue by M0RRiS0on** [sanjay900/guitar-configurator#13]
Rockband drums cymbals undefined
Can't bind them to pins
![изображение](https://user-images.githubusercontent.com/97400111/148691015-d6695311-f193-4d05-bc6f-7534e864802c.png)
In list view mode they are also absent
![изображение](https://user-images.githubusercontent.com/97400111/148691087-94bfbf26-bdfd-4f14-8975-0ec2afa976cc.png)

**Comment by M0RRiS0on** [comment]
If this program emulates ps3 drums maybe adding cymbals functionality possible by combo (DrumColor+modificator) for them. According to this forum: 
https://dwsk.proboards.com/thread/2258/playstation-4-rb4-pro-cymbals
About drums before ps4 version:
"Before, a tom was one button, and that same colored cymbal was that button + a shoulder bumper button, for example."

**Comment by sanjay900** [comment]
Ah yeah cymbals were one of those things I never added support for as the
code just wasn't designed for it at the time, I may eventually add it though

**Comment by M0RRiS0on** [comment]
Ok, hope my info can help somehow.  Will be waiting eagerly new updates!

**Comment by sanjay900** [comment]
Ive implemented drums in the new firmware that's being worked on with full cymbal support and all that, but there's still a lot more to implement before I can release that.
