### ISSUE TITLE
Arduino Uno freezes at 100% claiming it's waiting for reconnection

### ISSUE THREAD

**Issue by jrusse1** [sanjay900/guitar-configurator#17]
Both 8.5.4 and 8.5.5 result in the same screen after programming completes (pictured). No matter how many times I reset the Arduino, I get the same result and the program stops responding before it can get to the configuration step. 

[Here's what I see](https://imgur.com/a/cecOVXh)

**Comment by jrusse1** [comment]
I also received this but I'm not sure if it's related.
[The Error I receive when installing the program](https://imgur.com/a/cecOVXh)

**Comment by jrusse1** [comment]
UPDATE: It works with 8.4.5

**Comment by sanjay900** [comment]
fixed with https://github.com/sanjay900/guitar-configurator/releases/tag/v8.5.7
