### ISSUE TITLE
Green fret

### ISSUE THREAD

**Issue by 0Peligr0** [sanjay900/guitar-configurator#19]
The green fret doesnt work, what can I do?

**Comment by sanjay900** [comment]
How have you wired things, what arduino is it? Usually, a single fret not working is a wiring issue

**Comment by 0Peligr0** [comment]
> How have you wired things, what arduino is it? Usually, a single fret not working is a wiring issue

I think all the cables to the arduino are well connected because all the other buttons work.
Maybe is a problem of the connections of the guitar, but where can I find the blueprints of the guitar inner connections?

**Comment by sanjay900** [comment]
Oh wait is this using the Arduino as a wiitars adapter?

**Comment by sanjay900** [comment]
The pcb for the frets is pretty easy to understand just by looking, I don't think any blueprints exist

**Comment by 0Peligr0** [comment]
> The pcb for the frets is pretty easy to understand just by looking, I don't think any blueprints exist

It is easy but there is a black dot on the middle of the board and I cant see where the cables are going through. There is any way to chek the frets?

**Comment by sanjay900** [comment]
Oh wait what guitar is this?

**Comment by 0Peligr0** [comment]
> Oh wait what guitar is this?
> […](#)

Is the guitar hero 2 guitar the red one for the ps2

**Comment by sanjay900** [comment]
You can always work out the frets with a multimeter in continuity mode. It will beep when the two contacts are connected together, and you can use that to work out which pin is which. Could you send a photo of the fret pcb?

**Comment by 0Peligr0** [comment]
> You can always work out the frets with a multimeter in continuity mode. It will beep when the two contacts are connected together, and you can use that to work out which pin is which. Could you send a photo of the fret pcb?

![D26923FC-753D-43D1-8426-D3A489BD2CE7](https://user-images.githubusercontent.com/55929126/164894012-a1d954d1-5cc4-42b3-943e-591a174cae4f.jpeg)

**Comment by sanjay900** [comment]
does the guitar work okay on a console?

**Comment by sanjay900** [comment]
it looks like with that pcb, the pin all the way on the left is ground (the one with the thicker trace on the fret pcb), and green will be one of the three on the side you circled. should be easy enough to test between ground and the other pins to work out which one is green, and to work out if something is wrong with the fret itself

**Comment by sanjay900** [comment]
if you have the config tool open, what does it say in the top left corner?

**Comment by sanjay900** [comment]
Ah actually i might have just found a issue with my handling of PS2 controllers, can you try out the latest version of the tool for me? I could see it being the issue with your green fret not working.

**Comment by 0Peligr0** [comment]
> Ah actually i might have just found a issue with my handling of PS2 controllers, can you try out the latest version of the tool for me? I could see it being the issue with your green fret not working. Theres a button to update inside the config tool, atm the latest is 8.6.2.
> 
> https://github.com/sanjay900/guitar-configurator/releases/tag/v8.6.2

I just tried the new version and nothing, and in the left corner say 
![Uploading image.jpg…]()

**Comment by sanjay900** [comment]
that image does not seem to have loaded, can you try uploading it again

**Comment by 0Peligr0** [comment]
![Uploading B41D4C5E-71DE-4BE1-B0E9-6F6E3ED7D5F5.jpeg…]()

**Comment by 0Peligr0** [comment]
> that image does not seem to have loaded, can you try uploading it again

![B7448C09-6830-4239-ADF6-D03142B1A3F0](https://user-images.githubusercontent.com/55929126/164972000-a074627b-68e0-4487-a702-53abe0fff66e.jpeg)

**Comment by sanjay900** [comment]
ah, that unknown isnt helping us much! to confirm, your using this to make a ps2 controller adaptor right?

**Comment by 0Peligr0** [comment]
> ah, that unknown isnt helping us much! to confirm, your using this to make a ps2 controller adaptor right?

Yes

**Comment by sanjay900** [comment]
i presume whammy and tilt are also not working correct?

**Comment by 0Peligr0** [comment]
> i presume whammy and tilt are also not working correct?

They work well

**Comment by sanjay900** [comment]
ah okay, then this isnt the problem i thought it was

**Comment by sanjay900** [comment]
did tilt show up as a button or as a axis?

**Comment by 0Peligr0** [comment]
> did tilt show up as a button or as a axis?

No, the programs dont recognize it

**Comment by sanjay900** [comment]
but you just said that they work well?

**Comment by 0Peligr0** [comment]
> but you just said that they work well?

Axis, sorry

**Comment by sanjay900** [comment]
and whammy shows up as an axis too and works?

**Comment by 0Peligr0** [comment]
> and whammy shows up as an axis too and works?

Yes

**Comment by sanjay900** [comment]
interesting

**Comment by sanjay900** [comment]
> it looks like with that pcb, the pin all the way on the left is ground (the one with the thicker trace on the fret pcb), and green will be one of the three on the side you circled. should be easy enough to test between ground and the other pins to work out which one is green, and to work out if something is wrong with the fret itself

are you able to confirm the green fret is working with a multimeter?

**Comment by 0Peligr0** [comment]
I dont have a multimeter yet but Im trying to get one this week

**Comment by sanjay900** [comment]
ah okay, can you try the latest version (8.6.5) and let me know what the text in the top corner says now?

**Comment by 0Peligr0** [comment]
> ah okay, can you try the latest version (8.6.5) and let me know what the text in the top corner says now?

It sais the same

**Comment by sanjay900** [comment]
hmm, can you try unplugging and replugging the arduino from the computer

**Comment by sanjay900** [comment]
it really should not say Unknown, it should say guitar hero guitar or something

**Comment by 0Peligr0** [comment]
> it really should not say Unknown, it should say guitar hero guitar or something

Now it say PlayStation No Device

**Comment by sanjay900** [comment]
okay, that is different, are the other buttons still working?

**Comment by sanjay900** [comment]
do you have a discord? would be far easier to converse on that vs github, im sanjay900#5549, if not no problem

**Comment by sanjay900** [comment]
Can you try the latest version

**Comment by 0Peligr0** [comment]
> okay, that is different, are the other buttons still working?

yes, the other buttons sill working, I've tested the green fret first contact and it mark well like the others, but i dont know how to know if the resistors work, how can I measure it with the multimeter?
