### ISSUE TITLE
[Help]: Configurator Crashes After Flashing New Firmware

### ISSUE THREAD

**Issue by muskit** [sanjay900/guitar-configurator#23]
### Please describe your issue.

After updating the configurator and flashing updated firmware onto my Pro Micro, the Configurator crashes after clicking on "Start Configuring."
I also noticed that after firmware is flashed the top left status still displays "Outdated, Continue to update."

Running on v8.7.6, updated from v8.7.4 using the update prompt upon starting up.

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

arduino pro micro 3.3V

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
seems like when i redid the build scripts to add in all the various pi pico versions, something went wrong and the arduino builds dont have the correct version numbers anymore, im having a look now

**Comment by sanjay900** [comment]
there is a v8.7.7 compiling now that will fix this

**Comment by sanjay900** [comment]
give it 10m or so to compile and release

**Comment by sanjay900** [comment]
resolved by 8.7.7
