### ISSUE TITLE
[Request]: RF Setup with Pico

### ISSUE THREAD

**Issue by RE-Gaming** [sanjay900/guitar-configurator#24]
### Please describe your request.

Is RF TX and RX setup with Pico on the roadmap?

The setup is for Wii Guitar input --> PS3 output

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
Theres currently a rewrite on the roadmap, as the current RF code isn't great. Part of that rewrite will be a total rewrite of the RF code, and that will give it pico compatibility as well. This is a while away though.

**Comment by RE-Gaming** [comment]
No worries! The wired implementation currently works amazing. I've been able to get this to work with Rockband 4 on PS4.

**Comment by sanjay900** [comment]
Honestly I haven't tested this at all but if your lucky you might find that using the pins from here may just work 
https://github.com/sanjay900/Ardwiino/blob/master/src/pico/pins_arduino.h

**Comment by RE-Gaming** [comment]
I tested out the pinout you linked above but didn't get quite far enough to be able to test it.

When I program the receiver Pico, I set it up like I normally would the wired version. When I click program RF --> program transmitter I am able to select a second Pico but the program hangs after I choose to program the transmitter Pico.
![Get stuck on waiting for reconnection](https://user-images.githubusercontent.com/95144651/168953797-12ca1bf7-a39b-4e03-825b-4622001ae893.PNG)

The configurator hangs at "Waiting for Reconnection"

**Comment by sanjay900** [comment]
ah okay

**Comment by RE-Gaming** [comment]
Hello,
Any update on the timelines for this feature add?
Thanks!

**Comment by sanjay900** [comment]
none at this time

**Comment by sanjay900** [comment]
Finally actually getting around to writing something, so I will be able to see if I can get something that is just always stable

**Comment by sanjay900** [comment]
So a few updates
I finally got around to properly implementing RF yesterday, including the UI elements for it
![image](https://user-images.githubusercontent.com/1862720/229637217-2e87dc63-65bb-4a81-9dc3-404302d26d9e.png)
![image](https://user-images.githubusercontent.com/1862720/229637246-e0c6321b-0184-4f24-b5d7-ed87085306cf.png)

But for the pico specifically, i intend to also support something with the pico w. My intent is to support using Bluetooth, so you can build just the transmitter for PC use, but for console you you can then build a bluetooth receiver as well. I have the transmitter side of the bluetooth equation sorted and just need to write the receiver which i don't expect to take me long.

**Comment by sanjay900** [comment]
You can probably see why i was so hesistant to give you a timeline though, this stuff happens at a snails pace as i just put my free time into it

**Comment by sanjay900** [comment]
Yeah okay, i will be dropping RF support, its just such a mission to keep that working.
