### ISSUE TITLE
Can't enable APA102 LEDs on Arduino Uno board

### ISSUE THREAD

**Issue by NickBonet** [sanjay900/guitar-configurator#3]
One of my guitars is wired up to an Arduino Uno, and I wanted to test APA102 LEDs on it, but whenever I set the LED mode to APA102 and write the settings, the LED mode change doesn't actually save.

I'm able to enable APA102 LEDs on my Arduino Pro Micro clone board though, for reference.

**Comment by NickBonet** [comment]
I've tried on v8.0.0, v8.0.1, v8.0.2

**Comment by sanjay900** [comment]
Fixed with https://github.com/sanjay900/guitar-configurator/commit/1221f412837f68a0c659794e1644598ce5e36d81
Currently the fix is only on the preview build, which you can get at:
https://github.com/sanjay900/guitar-configurator/releases/tag/preview
