### ISSUE TITLE
8.8.7 killed whammy

### ISSUE THREAD

**Issue by puredave** [sanjay900/guitar-configurator#30]
8.8.7 - can configure whammy in tool without issue, however in USB controllers tools or in-game whammy shows no response. (Direct XInput)

8.8.5 - works as intended

**Comment by sanjay900** [comment]
what arduino

**Comment by puredave** [comment]
it was happening with pro micro v5 & pi pico, turns out it was 2 bad pots and not the 8.8.7 update! extremely unlucky :0
