### ISSUE TITLE
[Issue]: guitar crashing newer versions of clone hero

### ISSUE THREAD

**Issue by redstone47** [sanjay900/guitar-configurator#38]
### Please describe your issue.

when guitar is plugged in ch versions 1.0.0.3300 and newer crash

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
try ps3 rb mode

**Comment by redstone47** [comment]
still crashes

**Comment by sanjay900** [comment]
Thats pretty odd then since at that point the controller isn't special in comparison to any other controller out there.

**Comment by redstone47** [comment]
i tried to reset the firmware back to the normal pi pico one using guitar configurator and it would say it was finished but would still show up as a controller

**Comment by sanjay900** [comment]
You can just hold the bootsel button while plugging it into the of then anything will be able to program it again

**Comment by redstone47** [comment]
i did that and i still cant reset it

**Comment by sanjay900** [comment]
then something is wrong with your pico, as that mode is how they are programmed.
It should show up as a USB drive if you have done it correctly.

**Comment by sanjay900** [comment]
you did click save after writing PS3 RB mode right?

**Comment by sanjay900** [comment]
out of curiousity, if you have a spare pi pico, does it happen if you just program a pico with nothing hooked up to it?
would be interesting to work out if it happens with a new pico

**Comment by redstone47** [comment]
i did save after writing and i do have another pico

**Comment by redstone47** [comment]
it still isnt writing but i will try a different computer

**Comment by redstone47** [comment]
i dont know how but the issue fixed itself the only problem i can think of is that i somehow had like 7 different versions of guitar configurator installed

**Comment by sanjay900** [comment]
good to hear
