### ISSUE TITLE
Arduino UNO based guitar works outside of CH, but not in game.

### ISSUE THREAD

**Issue by NickBonet** [sanjay900/guitar-configurator#4]
Running v8.0.2 with an UNO based guitar, and for some reason no inputs register within Clone Hero.
Dropped back to 8.0.1 to test, everything appears to work normally on the board

**Comment by sanjay900** [comment]
What about the preview build?

**Comment by NickBonet** [comment]
I actually tried both 8.0.2 and preview build, since I used preview for the other fixes you put in, and re-flashed the UNO each time for testing purposes, but it would not work within Clone Hero. It worked fine checking USB game controller settings in Windows and checking button inputs though

**Comment by sanjay900** [comment]
Is clone hero binding it correctly? Does it all show up in the controller menu when you hit spacebar?

**Comment by NickBonet** [comment]
I would have to check again next time I disassemble the guitar, currently in the process of moving so not able to right at the moment. I remember it at least showing up as a guitar in game, don't think I saw controls actually bound though.

**Comment by sanjay900** [comment]
What operating system are you using also? I could see this happening on Linux

**Comment by sanjay900** [comment]
The latest build may have done something, it contains a bunch of fixes specifically for the UNO

**Comment by sanjay900** [comment]
Also, it was pointed out to me that leds weren't working on windows so that's been fixed now

**Comment by nikorev** [comment]
Can confirm pro micro flashed with xinput does not get detected in Ubuntu (works on Windows, haven't tested OSX).

Flashing to PS guitar works as an alternative, but would much rather prefer xinput mapping.

**Comment by sanjay900** [comment]
Update your kernel, they only started supporting my controllers recently

**Comment by nikorev** [comment]
Thanks @sanjay900 can confirm the controller works on Ubuntu 20.04's new v5 kernel vs Ubuntu 18.04's v4 kernel.
