### ISSUE TITLE
uno not programing correctly [Issue]: 

### ISSUE THREAD

**Issue by redstone47** [sanjay900/guitar-configurator#43]
### Please describe your issue.

when updating my guitar it goes through the whole "loading" process but after reconnecting it still says outdated and when i click configure guitar configurator crashes

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino uno

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Ugh not this again lol

**Comment by sanjay900** [comment]
Latest firmware?

**Comment by sanjay900** [comment]
Fixed by https://github.com/sanjay900/guitar-configurator/releases/tag/v8.9.4
