### ISSUE TITLE
[Issue]: guitar keeps "crashing"

### ISSUE THREAD

**Issue by redstone47** [sanjay900/guitar-configurator#48]
### Please describe your issue.

the guitar will randomly stop recognizing any button inputs and will continue holding down notes that where held down before. i also had another uno modded guitar do this and the only fix was to make a reset button for the arduino. 

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino uno

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
I guess the first thing i can say is don't use  unos if you can, use picos.
I'm working on a new firmware that will hopefully help with stuff like this but out of curiousity what pins are you using on the uno?

**Comment by redstone47** [comment]
i would have used a pico but i didnt have any and i already had the uno and the pin bindings are 6, 7, 4, 3, 12, 10, 11, 9, 8, and A0 for whammy.

**Comment by sanjay900** [comment]
One thing that you could possibly try is seeing if any of the older versions have this bug fixed?

**Comment by redstone47** [comment]
it has the problem on the old version too

**Comment by sanjay900** [comment]
its interesting right cause i know a lot of people with uno guitars that never had this issue, which uno revision have you got?

**Comment by redstone47** [comment]
its some random off brand of the rev 3 i think

**Comment by sanjay900** [comment]
@redstone47 i know its been a while, but are any of the newer versions working better for you?

**Comment by redstone47** [comment]
yes, the newer versions have been working alot better and i havent had any issues sence
