### ISSUE TITLE
[Request]: Led Brightness

### ISSUE THREAD

**Issue by jackw163** [sanjay900/guitar-configurator#50]
### Please describe your request.

Hi, 

I realise this could be permanently achieved via hardware, but could a led brightness slider be added for the led options in the guitar configurator? would then make it easy to adjust all led brightness's on the fly especially as you may want the Starpower a different brightness to the fret Leds or something.

Many Thanks
Jack

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

arduino pro micro 5V

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Are you talking about APA102s or normal leds?

**Comment by jackw163** [comment]
Both, but mostly normal leds, or even just a bright and dim setting

**Comment by sanjay900** [comment]
normal leds i can't really do anything about, as the microcontroller itself doesn't actually output anything for driving leds behind frets. You would have to change your resistor value to change brightness.

**Comment by jackw163** [comment]
No worries, As a side note, could APA102's also be used for lighting for
other parts of the guitar? or even just ambient lighting?

**Comment by sanjay900** [comment]
you can assign them to any button, i haven't really got any code for ambient stuff, but it would probably make more sense to drive them with another microcontroller if they are just always going to be the same colour

**Comment by jackw163** [comment]
Awesome, thanks for your replies they've really helped me plan my setup
