### ISSUE TITLE
[Request]: Support for Adafruit QT PY - SAMD21 board

### ISSUE THREAD

**Issue by Dark1886** [sanjay900/guitar-configurator#55]
### Please describe your request.

Requesting support for ADAFRUIT QT PY - SAMD21 board. 

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

N/A

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
I may look into this one day, but i don't own one of these, so its not something i can do easily.

**Comment by Dark1886** [comment]
I'll be getting one very soon and may see if I can manage some updates to
get it working, but I'll admit the depth of this project is a little
outside my typical software workloads.

**Comment by sanjay900** [comment]
Yeah I wouldn't recommend that with the current firmware it's very tied to
the Pico and the arduino

**Comment by Dark1886** [comment]
> Yeah I wouldn't recommend that with the current firmware it's very tied to the Pico and the arduino. Theres a rewrite on the way, and until that is done i would hold of editing anything, but once thats there it uses platform.io so things should be easier.
> […](#)

I’ve heard about a re-write, and I’m wondering when the ETA (Roughly) on that is? Sorry If i missed this mentioned somewhere.

**Comment by sanjay900** [comment]
Heh, theres no ETA

**Comment by Dark1886** [comment]
> Heh, theres no ETA, hence why you haven't seen one

No problem, if it was around the corner I would wait. I'll probably just end up with a different controller to use instead.
