### ISSUE TITLE
[Issue]: Stuck on programming USB controller

### ISSUE THREAD

**Issue by kizzoknight** [sanjay900/guitar-configurator#56]
### Please describe your issue.

using a arduino pro micro 3.3v gets to programming usb controller (%100) then doesnt do anything

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

arduino pro micro 3.3V

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
What's your computer see the device as after this point

**Comment by kizzoknight** [comment]
Apologise for some reason I needed to select 5v even tho I did it
previously on a board that was exact same that worked with 3.3v

**Comment by sanjay900** [comment]
Theres two different variants of the board, you must have brought a 3.3v one previously and a 5v one the second time, they look identical but have a single changed component hence you probably wouldn't have noticed the difference
