### ISSUE TITLE
[Issue]: Pre Release 

### ISSUE THREAD

**Issue by kizzoknight** [sanjay900/guitar-configurator#65]
### Please describe your issue.

Pre Release stuck on 0% extracting firmware

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Dont use it.

**Comment by sanjay900** [comment]
I was just trying to get a CI process working, it's not for use yet
