### ISSUE TITLE
[Issue]: Guide button presses frantically, practically useless

### ISSUE THREAD

**Issue by jwagriff** [sanjay900/guitar-configurator#69]
### Please describe your issue.

Just built a direct guitar, an am trying to bind a button to the guide button in the configuration. The button does get bound, but once it does, looking at game pad tester, the button is pressed for very short amounts of time despite being held down continuously/spam pressed.

it’s not a hardware problem, as I can re-bind the same pin to start and I have no issues there.

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
turn off map start + select to home, i suspect thats conflicting

**Comment by sanjay900** [comment]
Did this work?

**Comment by sanjay900** [comment]
I can confirm the guide button has no issues in the new firmware in development as i use it a lot when testing console stuff at the moment.

**Comment by sanjay900** [comment]
Did some rewrites of map start + select to home, it shouldnt flicker now but if you have it enabled then you will just find that you wont get any inputs from a physical guide button as both of these options can't be used at the same  time.
