### ISSUE TITLE
[Issue]: "GHTV" Button (LS Click) does not show up in configurator

### ISSUE THREAD

**Issue by ujicos** [sanjay900/guitar-configurator#76]
### Please describe your issue.

This renders the entire GHTV mode unplayable. I couldnt figure out how to build this as i am on windows, but this should be a simple fix as looking at the code the support is already there. Hovering on the button in the graphical preview does NOTHING, nor is it in the list view

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Guitar hero live support is broken in console anyways iirc

**Comment by ujicos** [comment]
> 

GHTV Reloaded is a community project that revived GHTV for RPCS3, Real PS3 Hardware, and Real Wii U Hardware.
Could you push a update so i can enable this button? It's really essential for me, and as far as i can tell, the support is already in the source code

**Comment by ujicos** [comment]
Alternatively, provide a way to generate a solution file so i can fix this myself

**Comment by sanjay900** [comment]
yeah no the source code you see there is completly irrelevant to the current build of the configuration tool. The source code you can see is unfinished and unusable.

**Comment by ujicos** [comment]
> 

I had tilt working just fine. All i need is the GHTV button to work.

Isn't this just the current 9.1.2 build source? a.k.a the same as whats up right now?

**Comment by sanjay900** [comment]
not even close

**Comment by ujicos** [comment]
Alright, Thank you very much.
I didnt intend to come off as rude in the case i did.

**Comment by sanjay900** [comment]
all good, you aren't the first one to ask for this, so i really should have done it earlier. Was hoping this firmware rewrite would be done by now but its taking longer than id like

**Comment by sanjay900** [comment]
If your curious, this is what the 9.1.3 is based on: https://github.com/sanjay900/guitar-configurator/tree/qt

**Comment by ujicos** [comment]
> If your curious, this is what the 9.1.3 is based on: https://github.com/sanjay900/guitar-configurator/tree/qt

I'll have a look. For now i am waiting for the build to succeed for Windows, since github decided it didnt want to build it lol

**Comment by sanjay900** [comment]
You can probably see why im trying to migrate away from this firmware lol

**Comment by ujicos** [comment]
> You can probably see why im trying to migrate away from this firmware lol

I would say yes, but i have zero experience in Qt.
I couldnt even start compiling after grabbing source, lol

**Comment by sanjay900** [comment]
this pretty much happens every time QT updates, and since its been a year since the last update there have been a few updates. For some reason its being more difficult than normal though

**Comment by sanjay900** [comment]
https://github.com/sanjay900/guitar-configurator/releases/tag/v9.1.5
that took more effort than i would have liked haha

**Comment by ujicos** [comment]
I regret to inform you the GHTV button is still not being recognized. Maybe i was wrong about it being LS?
The graphical view also doesnt have the button showing up, only list view, but i really dont care for that, just more-so mentioning it so you're aware.
