### ISSUE TITLE
[Request]: RP2040 Zero compatible?

### ISSUE THREAD

**Issue by Namrepus221** [sanjay900/guitar-configurator#77]
### Please describe your request.

Is the RP2040 Zero board compatible to use as a board for the guitar configurator or is it underpowered?

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

N/A

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Try it

**Comment by sanjay900** [comment]
Funny story, a mate of mine just asked me if i wanted an RP2040 zero, so i guess when that ships i will have one to test.

**Comment by Namrepus221** [comment]
Only reason I’m asking is it only has 2 GND pins and was worrried it would cause problems with wiring

**Comment by sanjay900** [comment]
you can wire as many things to a single ground as you want.
