### ISSUE TITLE
Experiencing erratic analog stick behavior on 8.4.7

### ISSUE THREAD

**Issue by NickBonet** [sanjay900/guitar-configurator#8]
Just upgraded to 8.4.7, and I noticed my analog stick started behaving very erratically. I tried the new calibration controls but even then the analog would only register some inputs and not others. I downgraded back to 8.,0.1 and reflashed my controller and the analog stick works perfectly again for reference.

**Comment by sanjay900** [comment]
Is this with with wii mode and a wiitar?

**Comment by NickBonet** [comment]
This is with a Wii LP, XInput Direct mode.


Get Outlook for Android

**Comment by sanjay900** [comment]
Are you using it as an adaptor or direct wired

**Comment by NickBonet** [comment]
It is directly wired.

**Comment by sanjay900** [comment]
when you calibrated it, how did you calibrate it? whats interesting is i have a guitar here where i have a analog stick bound, and after calibration it seems to work perfectly
