### ISSUE TITLE
[Issue]: it does not work correctly:

### ISSUE THREAD

**Issue by technopal** [sanjay900/guitar-configurator#80]
### Please describe your issue.

it does not work correctly:

w10

pi-pico
input: ps2 controller
output: gamepad

the pc detects it, but the left stick controls a left axis and a right axis, several buttons pressed, (Y B A RB LB).

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

PS2

**Comment by sanjay900** [comment]
is this a real or a knock off ps2 controller?

**Comment by technopal** [comment]
> is this a real or a knock off ps2 controller? And which gamepad output have you chosen?

I tried with 3 original controls, two from ps2 and one from ps1, I even tried with a blueretro in ps2 mode. gamepad input

**Comment by sanjay900** [comment]
I suspect this is fixed in the new firmware as that I've tested with PS2
and ps1 controllers. Can't give you an ETA on that though

**Comment by technopal** [comment]
> 

Thanks for answering, I'll wait for the new firmware.

**Comment by sanjay900** [comment]
@technopal fixed by https://github.com/sanjay900/guitar-configurator/releases/tag/v9.4.7
