### ISSUE TITLE
[Issue]: Arduino Uno Out of Date | Program Crashes when "Start Configuring"

### ISSUE THREAD

**Issue by TripleTell** [sanjay900/guitar-configurator#85]
### Please describe your issue.

Following this guide: https://sanjay900.github.io/guitar-configurator/guides/wii.html#steps
I am having trouble at step 11. 

Whenever I click "Start Configuring," the program closes/crashes.
![image](https://user-images.githubusercontent.com/132794043/236652518-706c1c2e-de01-48df-9abc-a034b8781c52.png)

Extra information that might be useful.

- When I start from the beginning, I do not have to put the board back in DFU mode. It automatically recognizes the board in DFU mode and continues unprompted.

- I have tried it with two separate Arduino Uno boards I had laying around, and I have the same outcome.

- I was able to get to the Configuring part the first time, but it did not have a picture of the guitar like the guide had.

- My Device Manager recognizes the Arduino as Ardwiino

- ![image](https://user-images.githubusercontent.com/132794043/236652625-dba832c3-7253-407f-a764-adb050e42f9b.png)

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

arduino uno

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by sanjay900** [comment]
Yeah i need to rebuild the uno code i think

**Comment by TripleTell** [comment]
Which older code should I use?

**Comment by sanjay900** [comment]
Anything before the xb360 fixes

**Comment by sanjay900** [comment]
Trying to release a fixed version but for some reason the macos builds have just stopped working out of nowhere :(

**Comment by sanjay900** [comment]
https://github.com/sanjay900/guitar-configurator/releases/tag/v9.1.16

**Comment by TripleTell** [comment]
Thanks so far! I downloaded v9.1.16 and the next issue arrises when i click "Write".

![image](https://user-images.githubusercontent.com/132794043/236706263-6332b296-1bb3-4b1c-97d2-766cfa7193fb.png)

My computer then has the sound alert as something disconnected and displays a "Controller disconnect" on the screen.

![image](https://user-images.githubusercontent.com/132794043/236706298-95773780-88eb-45df-8a5d-e62f1c8d133d.png)

Thoughts?

**Comment by sanjay900** [comment]
does it not connect back?

**Comment by sanjay900** [comment]
tbh, it looks like its all programmed anyways, what setting are you trying to write at the moment?

**Comment by TripleTell** [comment]
I don't know if it connects back or not. Should the program do anything different? I went into Clone Hero and the guitar wasn't recognized or working.

**Comment by sanjay900** [comment]
if you look in the top left corner of the tool, it says "wii no extension"
this means your wii guitar isnt being detected and you have something wired up wrong.

**Comment by sanjay900** [comment]
oh, which vcc did you use on the uno?

**Comment by sanjay900** [comment]
Which breakout are you using?

**Comment by TripleTell** [comment]
No breakout. Using wires to go directly from the Wii plug to the Arduino. Low quality photo below. 

![image](https://user-images.githubusercontent.com/132794043/236718328-a4b7d43b-57ed-4249-8742-8153f7317ffb.png)

**Comment by sanjay900** [comment]
I updated the instructions, your wiring isnt quite right.

**Comment by sanjay900** [comment]
If this continues to not work, then the problem may just be you poking wires at it like that, i know a lot of people that couldn't get that method working because the wires just didnt make good contact.

**Comment by sanjay900** [comment]
Actually, can i see a picture of the connector in the guitar neck please?

**Comment by TripleTell** [comment]
![image](https://user-images.githubusercontent.com/132794043/236720460-0e87d00a-05ad-48b2-9c95-b83cc2112e5e.png)

**Comment by sanjay900** [comment]
Have you got discord by any chance? If so add me, sanjay900#0001

**Comment by TripleTell** [comment]
The neck is plugged in when I upload and test. I added on discord.
